flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
  - derive-2.6.5
  - monadIO-0.11.1.0
  - rolling-queue-0.1
  - stm-2.5.0.0
  - haskell-src-exts-1.23.1
  - tasty-1.3.1
  - random-1.2.0
  - splitmix-0.1.0.1
resolver: lts-16.17
