flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- derive-2.6.5
- monadIO-0.11.1.0
- rolling-queue-0.1
- stm-2.5.0.0
- haskell-src-exts-1.23.1
- tasty-1.3.1
#resolver: lts-12.19
#resolver: lts-14.27
resolver: lts-16.17
